apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tserver
  template:
    metadata:
      labels:
        app: tserver
    spec:
      containers:
      - name: time-server
        image: time-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: time-server-service
spec:
  type: ClusterIP
  selector:
    app: tserver
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888